version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: retailflow_postgres
    environment:
      POSTGRES_USER: retailflow_user
      POSTGRES_PASSWORD: retailflow_password
      POSTGRES_DB: retailflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/warehouse/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data:
